### ISSUE TITLE
SubGenerator calls new Application

### ISSUE THREAD

**Issue by evandro-slv** [newaeonweb/generator-angm#1]
When adding a new module with the SubGenerator example:

```
yo angm:angm-module
```

It loads the generator's default prompt to create a new application:

```
     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `


You're using the official Angm-generator.
[?] What would you like to call your application? (Angmodular) 
```

**Comment by newaeonweb** [comment]
@FlashCube , i´m sorry! the bug fix was upload right now, please update your generator to 0.1.2. Thank you very much.

**Comment by emeacham** [comment]
Sorry to resurrect this, but it looks like it's still an issue.

--CORRECTION--
It is broken when you install via "npm install generator-angm", but seems to work find if you clone the project then use "npm link" from within your working copy.

**Comment by newaeonweb** [comment]
@emeacham did you get the last version from npm?

**Comment by newaeonweb** [comment]
@emeacham Hi, bug fixed finally!
