### ISSUE TITLE
Errors in jshint

### ISSUE THREAD

**Issue by diegohaz** [newaeonweb/generator-angm#3]
Linting Gruntfile.js ...ERROR
Running "jshint:gruntfile" (jshint) task
Linting Gruntfile.js ...ERROR
[L4:C15] W109: Strings must use singlequote.
  "use strict"; 
Linting Gruntfile.js ...ERROR
[L119:C1] W099: Mixed spaces and tabs.
                  'app/app.config.js',
Linting Gruntfile.js ...ERROR
[L119:C19] W015: Expected 'app/app.config.js' to have an indentation at 13 instead at 19.
                  'app/app.config.js',
Linting Gruntfile.js ...ERROR
[L162:C29] W109: Strings must use singlequote.
  grunt.registerTask("build", [
Linting Gruntfile.js ...ERROR
[L163:C13] W109: Strings must use singlequote.
    "jshint", 
Linting Gruntfile.js ...ERROR
[L164:C11] W109: Strings must use singlequote.
    "exec", 
Linting Gruntfile.js ...ERROR
[L165:C13] W109: Strings must use singlequote.
    "concat", 
Linting Gruntfile.js ...ERROR
[L166:C18] W109: Strings must use singlequote.
    "ngtemplates", 
Linting Gruntfile.js ...ERROR
[L167:C26] W109: Strings must use singlequote.
    "injector:production", 
Linting Gruntfile.js ...ERROR
[L168:C17] W109: Strings must use singlequote.
    "concurrent", 
Linting Gruntfile.js ...ERROR
[L169:C12] W109: Strings must use singlequote.
    "clean" 

Warning: Task "jshint:gruntfile" failed. Used --force, continuing.

Running "jshint:app" (jshint) task
Linting app/modules/home/homeCtrl.js ...ERROR
[L24:C16] W003: 'Home' was used before it was defined.
  function Home(homeService) {
Linting app/modules/home/homeCtrl.js ...ERROR
[L27:C36] W109: Strings must use singlequote.
    vm.title = "Hello, alpha-bank!"; 
Linting app/modules/home/homeCtrl.js ...ERROR
[L28:C25] W109: Strings must use singlequote.
    vm.version = "1.0.0"; 
Linting app/modules/home/homeModule.js ...ERROR
[L1:C10] W013: Missing space after 'function'.
(function() {
Linting app/modules/home/homeModule.js ...ERROR
[L12:C5] W015: Expected 'angular' to have an indentation at 3 instead at 5.
    angular.module('home', []);
Linting app/modules/home/homeService.js ...ERROR
[L17:C23] W003: 'homeService' was used before it was defined.
  function homeService($http) {
Linting app/modules/home/homeService.js ...ERROR
[L20:C17] W109: Strings must use singlequote.
      {"feature": "Implemented Best Practices, following: John Papa's Guide"},
Linting app/modules/home/homeService.js ...ERROR
[L20:C77] W109: Strings must use singlequote.
      {"feature": "Implemented Best Practices, following: John Papa's Guide"}, 
Linting app/modules/home/homeService.js ...ERROR
[L21:C17] W109: Strings must use singlequote.
      {"feature": "Using Controller AS syntax"},
Linting app/modules/home/homeService.js ...ERROR
[L21:C47] W109: Strings must use singlequote.
      {"feature": "Using Controller AS syntax"}, 
Linting app/modules/home/homeService.js ...ERROR
[L22:C17] W109: Strings must use singlequote.
      {"feature": "Wrap Angular components in an Immediately Invoked Function Expression (IIFE)"},
Linting app/modules/home/homeService.js ...ERROR
[L22:C97] W109: Strings must use singlequote.
      {"feature": "Wrap Angular components in an Immediately Invoked Function Expression (IIFE)"}, 
Linting app/modules/home/homeService.js ...ERROR
[L23:C17] W109: Strings must use singlequote.
      {"feature": "Declare modules without a variable using the setter syntax"},
Linting app/modules/home/homeService.js ...ERROR
[L23:C79] W109: Strings must use singlequote.
      {"feature": "Declare modules without a variable using the setter syntax"}, 
Linting app/modules/home/homeService.js ...ERROR
[L24:C17] W109: Strings must use singlequote.
      {"feature": "Using named functions"},
Linting app/modules/home/homeService.js ...ERROR
[L24:C42] W109: Strings must use singlequote.
      {"feature": "Using named functions"}, 
Linting app/modules/home/homeService.js ...ERROR
[L25:C17] W109: Strings must use singlequote.
      {"feature": "Including Unit test with Karma"},
Linting app/modules/home/homeService.js ...ERROR
[L25:C51] W109: Strings must use singlequote.
      {"feature": "Including Unit test with Karma"}, 
Linting app/modules/home/homeService.js ...ERROR
[L26:C17] W109: Strings must use singlequote.
      {"feature": "Including UI options for Bootstrap or Angular-Material"},
Linting app/modules/home/homeService.js ...ERROR
[L26:C75] W109: Strings must use singlequote.
      {"feature": "Including UI options for Bootstrap or Angular-Material"}, 
Linting app/modules/home/homeService.js ...ERROR
[L27:C17] W109: Strings must use singlequote.
      {"feature": "Including Angular-Material-Icons for Angular-Material UI"},
Linting app/modules/home/homeService.js ...ERROR
[L27:C77] W109: Strings must use singlequote.
      {"feature": "Including Angular-Material-Icons for Angular-Material UI"}, 
Linting app/modules/home/homeService.js ...ERROR
[L28:C17] W109: Strings must use singlequote.
      {"feature": "Dynamic Menu generator for both themes"},
Linting app/modules/home/homeService.js ...ERROR
[L28:C59] W109: Strings must use singlequote.
      {"feature": "Dynamic Menu generator for both themes"}, 
Linting app/modules/home/homeService.js ...ERROR
[L29:C17] W109: Strings must use singlequote.
      {"feature": "Grunt task for Production and Development"}
Linting app/modules/home/homeService.js ...ERROR
[L29:C62] W109: Strings must use singlequote.
      {"feature": "Grunt task for Production and Development"} 
Linting app/modules/home/homeService.js ...ERROR
[L36:C5] W026: Inner functions should be listed at the top of the outer function.
    function getFeaturesList() {
Linting app/modules/home/homeService.js ...ERROR
[L36:C29] W003: 'getFeaturesList' was used before it was defined.
    function getFeaturesList() {
Linting app/modules/home/homeService.js ...ERROR
[L37:C18] W033: Missing semicolon.
      return list 
Linting app/modules/layouts/nav-bar/navBarCtrl.js ...ERROR
[L24:C18] W003: 'NavBar' was used before it was defined.
  function NavBar(homeService, MenuService) {
Linting app/modules/layouts/nav-bar/navBarCtrl.js ...ERROR
[L27:C28] W109: Strings must use singlequote.
    vm.title = "alpha-bank"; 
Linting app/modules/layouts/nav-bar/navbarDirective.js ...ERROR
[L16:C18] W003: 'navBar' was used before it was defined.
  function navBar() {
Linting app/modules/layouts/nav-bar/navbarDirective.js ...ERROR
[L32:C5] W026: Inner functions should be listed at the top of the outer function.
    function link(scope, element, attrs, $location) {
Linting app/modules/layouts/nav-bar/navbarDirective.js ...ERROR
[L32:C18] W003: 'link' was used before it was defined.
    function link(scope, element, attrs, $location) {
Linting app/modules/layouts/nav-bar/navbarDirective.js ...ERROR
[L44:C21] W003: 'control' was used before it was defined.
    function control($scope, $location) {
Linting app/modules/layouts/nav-bar/navbarService.js ...ERROR
[L22:C16] W003: 'Menu' was used before it was defined.
  function Menu($http) {
Linting app/modules/layouts/nav-bar/navbarService.js ...ERROR
[L36:C6] W033: Missing semicolon.
    } 

Warning: Task "jshint:app" failed. Used --force, continuing.

**Comment by huseyinalp-zz** [comment]
same problem here +1

**Comment by newaeonweb** [comment]
@diegohaz , @huseyinalp ; checking this issue now

**Comment by newaeonweb** [comment]
@diegohaz , @diegohaz ; please update to version: generator-angm@1.0.4
jslint errors was fixed.
