### ISSUE TITLE
The app loads painfully slow

### ISSUE THREAD

**Issue by ebertulfo** [newaeonweb/generator-angm#4]
Do you have any advice how to address this issue?

**Comment by newaeonweb** [comment]
@edmeister18 ; checking this issue now

**Comment by newaeonweb** [comment]
@edmeister18; I simulate here everything is fine, did you mean the first time you use the generator?

**Comment by ebertulfo** [comment]
No man. It is slow everytime I refresh the page. 

```
On Tuesday, May 3, 2016 5:25 AM, fernando monteiro <notifications@github.com> wrote:
```

 @edmeister18; I simulate here everything is fine, did you mean the first time you use the generator?—

**Comment by newaeonweb** [comment]
@edmeister18 I will investigate further, in my tests is loading very quickly
