### ISSUE TITLE
Mssing comma in bower.json

### ISSUE THREAD

**Issue by homj** [newaeonweb/generator-angm#5]
There's a comma missing in https://github.com/newaeonweb/generator-angm/blob/master/app/templates/_bower.json
at line 25 which causes this error when setting up a new project with Angular UI Bootstrap and Angular Material selected as UI Frameworks:

```
bower EMALFORMED    Failed to read C:\Users\Johannes\workspace\TestApp\bower.json

Additional error details:
Unexpected string
```

**Comment by newaeonweb** [comment]
@homj ; please update to version 1.0.5.

**Comment by homj** [comment]
@newaeonweb I'm using 1.0.6, issue is still there
