### ISSUE TITLE
Especificar pasta ao criar modulo

### ISSUE THREAD

**Issue by ricatom** [newaeonweb/generator-angm#8]
Parabéns pela sua iniciativa, tem ajudado muito.

Existe alguma forma de informar uma pasta ao criar novo modulo ?

Algo como:
yo angm:angm-module /Minhapasta/NomedoModulo

Ficando:
app
|__modules
    |__minhapasta
        |__modulocriado

**Comment by newaeonweb** [comment]
@ricardotomim Obrigado. O gerador cria a pasta automaticamente utilizando o nome do modulo, infelizmente não tem como utilizar outro nome, apenas se vc criar de forma manual.
